export default {
  ac_charge_energy_daily: { name: 'AC Charge Energy (Daily)', topic: 'ac_charge_energy_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  battery_energy_charge_daily: { name: 'Battery Energy Charge (Daily)', topic: 'battery_energy_charge_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  battery_energy_charge_solar_daily: { name: 'Battery Energy Charge Solar (Daily)', topic: 'battery_energy_charge_solar_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  battery_energy_cost_daily: { name: 'Battery Energy Cost (Daily)', topic: 'battery_energy_cost_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: '$', device_class: 'monetary', accuracy_decimals: 2, value_template: '{{ float(value) | round(2) }}' } },
  battery_energy_discharge_daily: { name: 'Battery Energy Discharge (Daily)', topic: 'battery_energy_discharge_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  grid_energy_cost_daily: { name: 'Grid Energy Cost (Daily)', topic: 'grid_energy_cost_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: '$', device_class: 'monetary', accuracy_decimals: 2, value_template: '{{ float(value) | round(2) }}' } },
  grid_energy_daily: { name: 'Grid Energy (Daily)', topic: 'grid_energy_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  load_energy_cost_daily: { name: 'Load Energy Cost (Daily)', topic: 'load_energy_cost_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: '$', device_class: 'monetary', accuracy_decimals: 2, value_template: '{{ float(value) | round(2) }}' } },
  load_energy_daily: { name: 'Load Energy (Daily)', topic: 'load_energy_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  load_energy_solar_daily: { name: 'Load Energy Solar (Daily)', topic: 'load_energy_solar_daily', id: 'energy', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  load_energy_solar_dc: { name: 'Load Energy Solar (DC)', topic: 'load_energy_solar_dc', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  load_energy_grid_daily: { name: 'Load Energy Grid (Daily)', topic: 'load_energy_grid_daily', id: 'energy', main: 'both', config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  pv_energy_daily: { name: 'PV Energy (Daily)', topic: 'pv_energy_daily', id: 'energy', main: 'both', individual: true, config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  pv_energy_ac_daily: { name: 'PV Energy Daily AC (Daily)', topic: 'pv_energy_ac_daily', id: 'energy', main: 'both', individual: true, config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  pv_energy_dc_daily: { name: 'PV Energy Daily DC (Daily)', topic: 'pv_energy_dc_daily', id: 'energy', main: 'both', individual: true, config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  pv_energy_daily_1: { name: 'PV Energy 1 (Daily)', topic: 'pv_energy_daily_1', id: 'energy', individual: true, config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } },
  pv_energy_daily_2: { name: 'PV Energy 2 (Daily)', topic: 'pv_energy_daily_2', id: 'energy', individual: true, config: { state_class: 'total', unit_of_measurement: 'kWh', device_class: 'energy' } }
}
